sudo: required
services:
 - docker

language: go
go:
  - 1.11

jobs:
  include:

    - stage: Tests
      name: Unit Tests
      before_install:
        - go get github.com/mattn/goveralls
      install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure -v
      script:
        - go test -v -covermode=count -coverprofile=coverage.out ./...
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

    - stage: Build and publish
      name: Docker Hub
      install: skip
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - export REPO=$DOCKER_USER/prometheus-alert-webhooker
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
        - echo $REPO:$TAG
        - docker build -f Dockerfile -t $REPO:$TAG .
        - docker push $REPO