[[constraint]]
  branch = "master"
  name = "github.com/bndr/gojenkins"

[[constraint]]
  name = "github.com/coocood/freecache"
  version = "1.0.1"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/copier"

[[constraint]]
  name = "github.com/prometheus/alertmanager"
  version = "0.15.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.0-pre1"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/go-telegram-bot-api/telegram-bot-api"

[prune]
  unused-packages = true
